[project]
name = "causal-ai-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dowhy>=0.14",
    "graphviz>=0.21",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.8",
    "pgmpy>=1.0.0",
    "torch>=2.9.1",
]
